---
- name: upload mongo docker-compose.yml from template
  template: 
    src: docker-compose.yml.j2
    dest: '{{ mongo_install_dir }}/docker-compose.yml'

- name: mongo start 
  shell: "docker-compose up -d" 
  args:
    chdir: "{{ mongo_install_dir  }}"
