---
# defaults file for harbor
harbor_version: v1.10.10
harbor_install_url: https://github.com/goharbor/harbor/releases/download/{{ harbor_version }}/harbor-offline-installer-{{ harbor_version }}.tgz
harbor_install_file: harbor-offline-installer-{{ harbor_version }}.tgz
harbor_install_dir: /home/ubuntu/

## harbor.yml 
harbor_hostname: 13.55.212.137
harbor_http_port: 80 

#harbor
#harbor_https_port: 443
#harbor_certi_path: /
#private_key_path: /

harbor_admin_pw: admin12345